#!/bin/sh
# Installs a desktop launcher for Vesktop-Canary that runs the musl Electron build,
# so it shows up in rofi / your app launcher. For musl systems where the packaged
# glibc binaries can't run. Everything lands in ~/.local (no root, fully reversible).
#
#   sh scripts/musl/install.sh            install / update
#   sh scripts/musl/install.sh --uninstall   remove
set -eu

REPO="$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)"
APP_ID="vesktop-canary"
BIN="$HOME/.local/bin/$APP_ID"
DESKTOP="$HOME/.local/share/applications/$APP_ID.desktop"
ICON_DIR="$HOME/.local/share/icons/hicolor/scalable/apps"
ICON="$ICON_DIR/$APP_ID.svg"

if [ "${1:-}" = "--uninstall" ]; then
    rm -f "$BIN" "$DESKTOP" "$ICON"
    update-desktop-database "$HOME/.local/share/applications" 2>/dev/null || true
    echo "Removed Vesktop-Canary launcher."
    exit 0
fi

echo "Building Vesktop-Canary..."
cd "$REPO"
if [ ! -x "$REPO/.electron-musl/electron.sh" ]; then
    echo "Setting up the musl Electron runtime (first run, downloads Alpine's electron)..."
    pnpm setup:musl
fi
pnpm build

mkdir -p "$(dirname "$BIN")" "$(dirname "$DESKTOP")" "$ICON_DIR"

cat > "$BIN" <<LAUNCHER
#!/bin/sh
# Generated by scripts/musl/install.sh
exec "$REPO/.electron-musl/electron.sh" "$REPO" "\$@"
LAUNCHER
chmod +x "$BIN"

cp "$REPO/build/icon.svg" "$ICON"

cat > "$DESKTOP" <<DESKTOPENTRY
[Desktop Entry]
Type=Application
Name=Vesktop Canary
GenericName=Internet Messenger
Comment=Discord client fork with privacy and OPSEC features
Exec=$BIN %U
Icon=$APP_ID
Terminal=false
Categories=Network;InstantMessaging;Chat;
Keywords=discord;vencord;vesktop;chat;
MimeType=x-scheme-handler/discord;
StartupWMClass=vesktop-canary
SingleMainWindow=true
DESKTOPENTRY

update-desktop-database "$HOME/.local/share/applications" 2>/dev/null || true
gtk-update-icon-cache -f -t "$HOME/.local/share/icons/hicolor" 2>/dev/null || true

echo "Installed. Search 'Vesktop Canary' in rofi."
echo "  launcher: $BIN"
echo "  desktop:  $DESKTOP"
echo "Re-run this script after pulling updates to rebuild."
